export const GET_DATA = 'dataReducer/GET-DATA'
export const ADD_HERO_NICKNAME = 'dataReducer/ADD-HERO-NICKNAME'
export const SAVE_PHOTO_SUCCESS = 'dataReducer/SAVE-PHOTO-SUCCESS'
export const SET_HERO_ID = 'dataReducer/SET-HERO-ID'
export const SET_HERO_FEATURE = 'dataReducer/SET-HERO-FEATURE'
export const DELETE_HERO_SUCCESS = 'dataReducer/DELETE-HERO-SUCCESS'
